services:
  fks_nginx:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Toronto
      FKS_DOMAIN_TEST: "fkstrading.test"
      FKS_DOMAIN_PROD: "fkstrading.xyz"
    user: root
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks: [fks_net]
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  ssl_certs:

networks:
  fks_net:
    name: fks_net
    external: true