worker_processes 1;
error_log stderr;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    access_log /dev/stdout;
    
    server {
        listen 80;
        server_name localhost;
        
        location / {
            return 200 '{"service":"fks-nginx","status":"healthy"}';
            add_header Content-Type application/json;
        }
    }
}
