# ============================================================
# Node Network Configuration
# ============================================================

# Global network settings
network:
  name: "FKS Trading Network"
  version: "1.0.0"
  protocol_version: "1.0"
  domain: "fks.network"
  max_connections: 1000
  ping_interval_ms: 10000
  discovery_interval_ms: 30000
  timeout_ms: 5000
  reconnect_attempts: 3
  reconnect_delay_ms: 3000

# Registry node configuration
registry:
  enabled: true
  host: "0.0.0.0"
  port: 7000
  node_id: "registry"
  region: "global"
  role: "registry"
  max_nodes: 100
  auth_required: false
  log_level: ${APP_LOG_LEVEL:-INFO}
  storage_path: "/app/data/registry"
  health_check_endpoint: "/health"
  metrics_endpoint: "/metrics"

# Node definitions by region
nodes:
  # Toronto node
  tor:
    enabled: true
    node_id: "tor1"
    region: "ca"
    host: "0.0.0.0"
    port: 7000
    role: "edge"
    registry_url: "http://node_registry:7000"
    log_level: ${APP_LOG_LEVEL:-INFO}
    storage_path: "/app/data/node-tor"
    health_check_endpoint: "/health"
    metrics_endpoint: "/metrics"

  # New York node
  nyc:
    enabled: true
    node_id: "nyc1"
    region: "us-east"
    host: "0.0.0.0"
    port: 7001
    role: "edge"
    registry_url: "http://node_registry:7000"
    log_level: ${APP_LOG_LEVEL:-INFO}
    storage_path: "/app/data/node-nyc"
    health_check_endpoint: "/health"
    metrics_endpoint: "/metrics"
    
  # London node
  lon:
    enabled: true
    node_id: "lon1"
    region: "uk"
    host: "0.0.0.0"
    port: 7002
    role: "edge"
    registry_url: "http://node_registry:7000"
    log_level: ${APP_LOG_LEVEL:-INFO}
    storage_path: "/app/data/node-lon"
    health_check_endpoint: "/health"
    metrics_endpoint: "/metrics"
    
  # Sydney node
  syd:
    enabled: true
    node_id: "syd1"
    region: "au"
    host: "0.0.0.0"
    port: 7003
    role: "edge"
    registry_url: "http://node_registry:7000"
    log_level: ${APP_LOG_LEVEL:-INFO}
    storage_path: "/app/data/node-syd"
    health_check_endpoint: "/health"
    metrics_endpoint: "/metrics"
    
  # Tokyo node
  tyo:
    enabled: true
    node_id: "tyo1"
    region: "jp"
    host: "0.0.0.0"
    port: 7004
    role: "edge"
    registry_url: "http://node_registry:7000"
    log_level: ${APP_LOG_LEVEL:-INFO}
    storage_path: "/app/data/node-tyo"
    health_check_endpoint: "/health"
    metrics_endpoint: "/metrics"
    
  # Frankfurt node
  fra:
    enabled: true
    node_id: "fra1"
    region: "de"
    host: "0.0.0.0"
    port: 7005
    role: "edge"
    registry_url: "http://node_registry:7000"
    log_level: ${APP_LOG_LEVEL:-INFO}
    storage_path: "/app/data/node-fra"
    health_check_endpoint: "/health"
    metrics_endpoint: "/metrics"
    
  # Chicago node (CME)
  chi:
    enabled: true
    node_id: "chi1"
    region: "us-central"
    host: "0.0.0.0"
    port: 7006
    role: "edge"
    registry_url: "http://node_registry:7000"
    log_level: ${APP_LOG_LEVEL:-INFO}
    storage_path: "/app/data/node-chi"
    health_check_endpoint: "/health"
    metrics_endpoint: "/metrics"
    exchange_focus: "CME"  # Chicago Mercantile Exchange

# Security settings
security:
  auth_enabled: false
  encryption_enabled: false
  tls_enabled: false
  
  # TLS settings (when enabled)
  tls:
    cert_dir: "/app/config/certs"
    ca_file: "ca.crt"
    cert_file: "node.crt"
    key_file: "node.key"
    verify_peer: true
    
  # Authentication settings (when enabled)
  auth:
    method: "token"
    token_expiry_seconds: 86400
    refresh_token_enabled: true
    token_file: "/app/config/auth/tokens.json"

# Network capabilities
capabilities:
  data_replication: true
  load_balancing: true
  failover: true
  auto_discovery: true
  metrics_collection: true
  health_monitoring: true

# Performance settings
performance:
  max_message_size_kb: 1024
  max_batch_size: 100
  worker_threads: 4
  io_threads: 2
  buffer_size_kb: 4096
  connection_backlog: 128
  
# Data processing
data_processing:
  compression_enabled: true
  compression_level: 6
  compression_algorithm: "gzip"
  serialization_format: "json"
  batch_processing: true
  
# Logging configuration
logging:
  file_enabled: true
  console_enabled: true
  log_format: "json"
  log_dir: "/app/logs"
  max_log_files: 10
  max_file_size_mb: 100
  metrics_logging_interval_seconds: 60
  
# Storage configuration
storage:
  persistence_enabled: true
  data_dir: "/app/data"
  backup_enabled: true
  backup_interval_hours: 24
  backup_dir: "/app/backups"
  
# API configuration
api:
  enabled: true
  cors_enabled: true
  allowed_origins: "*"
  rate_limit_enabled: true
  rate_limit_requests_per_minute: 60
  documentation_enabled: true