name: fks_nginx CI

concurrency:
  group: fks_nginx-ci-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    paths:
      - 'config/**'
      - 'docker/**'
      - 'Dockerfile'
      - '.github/workflows/fks_nginx-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'config/**'
      - 'docker/**'
      - 'Dockerfile'
      - '.github/workflows/fks_nginx-ci.yml'
  workflow_dispatch: {}

jobs:
  test:
    name: Configuration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Validate Nginx configuration syntax
        run: |
          # Install nginx for syntax checking
          sudo apt-get update
          sudo apt-get install -y nginx
          
          # Test configuration files
          for conf_file in config/*.conf; do
            if [ -f "$conf_file" ]; then
              echo "Testing $conf_file..."
              nginx -t -c "$(pwd)/$conf_file" || echo "Warning: $conf_file may need adjustment"
            fi
          done

      - name: Check for common configuration issues
        run: |
          echo "Checking for common Nginx configuration patterns..."
          # Check for missing semicolons, brackets, etc.
          find config/ -name "*.conf" -exec grep -H "server_name.*[^;]$" {} \; | head -10 || echo "No missing semicolons found"

  docker-build:
    name: Docker Build & Smoke
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 15
    env:
      SERVICE_SLUG: nginx
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: local/fks
          tags: |
            type=ref,event=branch,prefix=${{ env.SERVICE_SLUG }}-
            type=sha,prefix=${{ env.SERVICE_SLUG }}-
            type=raw,value=${{ env.SERVICE_SLUG }}-latest

      - name: Build image (no push)
        uses: docker/build-push-action@v5
        with:
            context: .
            file: Dockerfile
            push: false
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            build-args: |
              SERVICE_RUNTIME=nginx
              SERVICE_TYPE=nginx
              BUILD_TYPE=web

      - name: Smoke test
        run: |
          TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
          docker run -d --rm -p 8080:80 --name fks_nginx_test "$TAG"
          echo 'Waiting for nginx server...'
          for i in {1..15}; do
            sleep 2
            if curl -sf http://localhost:8080 > /dev/null; then
              echo 'Nginx server responded successfully'
              break
            fi
            if [ $i -eq 15 ]; then 
              echo 'Nginx server failed to respond'
              docker logs fks_nginx_test || true
              exit 1
            fi
          done
          docker logs fks_nginx_test | tail -n 20 || true
          docker stop fks_nginx_test

      - name: Export image artifact
        run: |
          docker save $(echo "${{ steps.meta.outputs.tags }}" | head -n1) | gzip > fks_nginx-image.tar.gz

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: fks_nginx-image
          path: fks_nginx-image.tar.gz
